# Generated by Django 3.2.5 on 2021-07-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdonisSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('migration_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adonis_schema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoodImages',
            fields=[
                ('imageid', models.AutoField(db_column='imageId', primary_key=True, serialize=False)),
                ('foodid', models.IntegerField(db_column='foodId')),
                ('path', models.CharField(max_length=600)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'food_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('foodid', models.AutoField(db_column='foodId', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('categoryname', models.CharField(db_column='categoryName', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'foods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.IntegerField(blank=True, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(db_column='OrderId', primary_key=True, serialize=False)),
                ('time_ordered', models.TimeField(blank=True, null=True)),
                ('time_deliverd', models.TimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=80)),
                ('is_revoked', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('isadmin', models.IntegerField(blank=True, db_column='isAdmin', null=True)),
                ('issuperadmin', models.IntegerField(blank=True, db_column='isSuperAdmin', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
